### ISSUE TITLE
CC, CCI, listener, (tag, flag)

### ISSUE THREAD

**Issue by xorgxx** [jacquesndl/MailerBundle#2]
Hi looking very attractive to use !!! do it have possibility to add CC, CCI ? also do you plan to put some listener, exp : to send copy automatic to same admin ..... with flag ?

Thank

**Comment by jacquesndl** [comment]
Hello @xorgxx ,

This bundle uses the `Symfony Mailer Component` .
`Jacquesndl\MailerBundle\Message\TemplatedEmail` inherits from `Symfony\Component\Mime\Email`, so you already can use the `cc()` or  `bcc()` methods. See the documentation below :
[https://symfony.com/doc/current/mailer.html#creating-sending-messages](https://symfony.com/doc/current/mailer.html#creating-sending-messages)

The component already triggers an event when you call the `send()` method.
I use it once in the bundle [https://github.com/jacquesndl/MailerBundle/blob/master/src/EventListener/MessageListener.php](https://github.com/jacquesndl/MailerBundle/blob/master/src/EventListener/MessageListener.php). Maybe it was enough for your use cases.

**Comment by xorgxx** [comment]
thank i will look all this
